const GAME_CATEGORIES = [
  {
    id: "lugares",
    name: "Lugares",
    emoji: "📍",
    words: [
      "Escola", "Hospital", "Aeroporto", "Praia", "Shopping", "Supermercado",
      "Farmácia", "Biblioteca", "Cinema", "Teatro", "Restaurante", "Padaria",
      "Parque", "Igreja", "Academia", "Banco", "Correio", "Delegacia",
      "Posto de gasolina", "Hotel", "Rodoviária", "Estação de trem", "Metrô", "Museu",
      "Castelo", "Fazenda", "Zoológico", "Aquário", "Salão de beleza", "Barbearia",
      "Escritório", "Fábrica", "Universidade", "Creche", "Pet shop", "Feira",
      "Camping", "Ilha", "Floresta", "Deserto"
    ]
  },
  {
    id: "acoes",
    name: "Ações",
    emoji: "🎭",
    words: [
      "Trocar pneu", "Dar marcha à ré", "Jogar videogame", "Tirar selfie", "Fazer compras",
      "Montar móvel", "Pescar", "Acampar", "Surfar", "Remar", "Estacionar o carro",
      "Pegar a carteira", "Entrar na reunião", "Alcançar uma prateleira", "Tirar do forno",
      "Arrumar a cama", "Lavar a louça", "Lavar roupa", "Passar roupa", "Dobrar roupa",
      "Varrer o chão", "Passar pano", "Tirar o lixo", "Guardar as compras", "Trocar uma lâmpada",
      "Abrir a geladeira", "Fechar a cortina", "Regar as plantas", "Aspirar o tapete", "Lavar a janela",
      "Limpar o espelho", "Organizar o armário", "Trocar o lençol", "Pendurar roupa", "Guardar brinquedos",
      "Escovar os dentes", "Pentear o cabelo", "Cortar as unhas", "Fazer a barba", "Passar perfume",
      "Tomar banho", "Secar o cabelo", "Passar maquiagem", "Colocar lente de contato", "Fazer skincare",
      "Fazer uma ligação", "Atender o telefone", "Enviar mensagem", "Tirar uma foto", "Gravar um vídeo",
      "Digitar uma senha", "Carregar o celular", "Abrir um aplicativo", "Fechar um aplicativo", "Escanear um QR Code",
      "Fazer uma videochamada", "Tirar print", "Procurar Wi-Fi", "Instalar um aplicativo", "Desbloquear o celular",
      "Abastecer o carro", "Lavar o carro", "Empurrar o carro", "Colocar o cinto", "Calibrar o pneu",
      "Buzinar", "Trocar de marcha", "Abrir o porta-malas", "Fechar o porta-malas", "Ligar o carro",
      "Desligar o carro", "Chamar um guincho",
      "Jogar futebol", "Jogar vôlei", "Jogar basquete", "Jogar tênis", "Jogar boliche",
      "Andar de bicicleta", "Andar de skate", "Empinar pipa", "Fazer embaixadinhas", "Cobrar um pênalti",
      "Defender um pênalti", "Levantar peso", "Pular corda", "Nadar", "Mergulhar",
      "Escalar", "Patinar", "Fazer yoga",
      "Fazer café", "Fazer pipoca", "Fritar um ovo", "Assar um bolo", "Cortar uma cebola",
      "Espremer um limão", "Abrir uma lata", "Mexer a panela", "Servir comida", "Descascar uma banana",
      "Ralar queijo", "Bater uma massa", "Temperar a comida", "Virar panqueca", "Experimentar a comida",
      "Assinar um documento", "Bater ponto", "Dar uma aula", "Fazer uma prova", "Ler um livro",
      "Escrever uma carta", "Apresentar um trabalho", "Resolver uma conta", "Carimbar um papel", "Grampear folhas",
      "Digitar no computador", "Fazer uma entrevista", "Receber uma ligação", "Entregar um relatório", "Fazer uma apresentação",
      "Pisar no LEGO", "Levar um susto", "Fazer careta", "Dar cambalhota", "Contar um segredo",
      "Pedir silêncio", "Dar tchau", "Fazer pose", "Engolir um mosquito", "Escorregar na banana",
      "Tropeçar", "Bocejar", "Espirrar", "Tossir", "Gargalhar",
      "Chorar", "Cochilar", "Fugir de uma abelha", "Fingir dormir", "Fingir desmaiar",
      "Farejar", "Espionar", "Disfarçar", "Investigar", "Negociar",
      "Convencer", "Celebrar", "Perseguir", "Vigiar", "Escapar",
      "Hipnotizar", "Equilibrar", "Flutuar", "Cambalear", "Gaguejar",
      "Assobiar", "Resmungar", "Implorar", "Cumprimentar", "Alongar"
    ]
  },
  {
    id: "adjetivos",
    name: "Adjetivos",
    emoji: "✨",
    words: [
      "Feliz", "Triste", "Bravo", "Calmo", "Ansioso", "Corajoso",
      "Medroso", "Rápido", "Lento", "Alto", "Baixo", "Forte",
      "Fraco", "Inteligente", "Distraído", "Engraçado", "Sério", "Generoso",
      "Egoísta", "Paciente", "Impaciente", "Tímido", "Extrovertido", "Elegante",
      "Desleixado", "Organizado", "Bagunceiro", "Gentil", "Mal-humorado", "Curioso",
      "Criativo", "Preguiçoso", "Agitado", "Silencioso", "Barulhento", "Otimista",
      "Pessimista", "Educado", "Teimoso", "Amigável",
      "Cansado", "Faminto", "Surpreso", "Assustado", "Confuso",
      "Desconfiado", "Envergonhado", "Orgulhoso", "Vaidoso", "Exausto",
      "Estressado", "Aliviado", "Apaixonado", "Fofoqueiro", "Dramático",
      "Chato", "Fofo", "Maluco", "Sonolento", "Alegre",
      "Esperto", "Desajeitado", "Frio", "Calorento", "Mentiroso",
      "Fiel", "Invejoso", "Chorão", "Estiloso", "Doido"
    ]
  },
  {
    id: "profissoes",
    name: "Profissões",
    emoji: "💼",
    words: [
      "Médico", "Enfermeiro", "Professor", "Advogado", "Engenheiro", "Programador",
      "Dentista", "Veterinário", "Policial", "Bombeiro", "Piloto", "Comissário de bordo",
      "Motorista", "Padeiro", "Cozinheiro", "Garçom", "Mecânico", "Eletricista",
      "Pintor", "Pedreiro", "Arquiteto", "Jornalista", "Fotógrafo", "Ator",
      "Cantor", "Dançarino", "Farmacêutico", "Psicólogo", "Recepcionista", "Secretário",
      "Contador", "Carteiro", "Cabeleireiro", "Barbeiro", "Segurança", "Juiz",
      "Astronauta", "Cientista", "Agricultor", "Vendedor", "Maestro", "Mágico",
      "Palhaço", "Pescador", "Florista", "Encanador", "Jardineiro", "Pizzaiolo",
      "Sorveteiro", "Guarda-vidas", "Atleta", "Detetive", "Espião", "Acrobata",
      "Astrônomo", "Mergulhador", "Guia turístico", "Locutor", "Modelo"
    ]
  },
  {
    id: "pessoas",
    name: "Pessoas",
    emoji: "👥",
    words: [
      "Bebê", "Criança", "Adolescente", "Mãe", "Pai", "Avó",
      "Avô", "Irmão", "Irmã", "Tio", "Tia", "Primo",
      "Prima", "Vizinho", "Amigo", "Namorado", "Namorada", "Noivo",
      "Noiva", "Marido", "Esposa", "Professor", "Aluno", "Chefe",
      "Funcionário", "Cliente", "Turista", "Atleta", "Músico", "Artista",
      "Fofoqueiro", "Nerd", "Gênio", "Bilionário", "Influenciador",
      "Gamer", "Fitness", "Sósia", "Herói", "Vilão",
      "Príncipe", "Princesa", "Rei", "Rainha", "Guarda",
      "Colega", "Convidado", "Papagaio", "Zumbi", "Vampiro",
      "Fantasma", "Bruxa", "Pirata", "Anjo", "Demônio",
      "Alienígena", "Robô", "Hacker", "Vigarista", "Celebridade",
      "Mímico", "Paparazzo", "Fã", "Solteiro", "Chefinho",
      "Prisioneiro", "Capitão", "Bebum", "Ladrão", "Aventureiro"
    ]
  },
  {
    id: "marcas",
    name: "Marcas",
    emoji: "🏷️️",
    words: [
      "Apple", "Samsung", "Motorola", "Xiaomi", "LG", "Sony", "Nintendo", "PlayStation", "Xbox", "Google", "Amazon",
      "Nike", "Adidas", "Puma", "Havaianas", "Reebok", "Umbro", "Topper", "Penalty", 
      "Renner", "C&A", "Riachuelo", "Zara", "Melissa", "Crocs", "Vans", "Converse", 
      "Ray-Ban", "Oakley", "Lacoste", "Calvin Klein", "Hering",
      "Coca-Cola", "Pepsi", "McDonald's", "Burger King", "KFC", "Subway",
      "Nestlé", "Lacta", "Garoto", "Bauducco", "Red Bull", "Fanta", "Sprite", 
      "Guaraná Antarctica", "Heineken", "Amstel", "Skol", "Brahma", "Budweiser", 
      "Doritos", "Cheetos", "Bis", "KitKat", "Kinder", "Nutella", "Oreo", 
      "Melitta", "Três Corações", "Cacau Show", "Kopenhagen",
      "Sadia", "Perdigão", "Seara", "Danone", "Danoninho", "Activia", "Parmalat",
      "Colgate", "Oral-B", "Gillette", "Nivea", "Omo", "Ypê", "Boticário", "Natura", "Avon",
      "Itaú", "Bradesco", "Santander", "Banco do Brasil", "Caixa", "Mastercard", "Visa", "PayPal",
      "Volkswagen", "Toyota", "Honda", "Ford", "Chevrolet", "Hyundai", "Fiat", "Jeep", "Renault", "Nissan",
      "Disney", "Marvel", "Warner Bros", "Ri Happy", "Casas Bahia", "Magalu", 
      "Americanas", "Vivara", "Pandora", "Fast Shop", "Pichau", "Kabum", "Estrela", "Grow"
    ]
  },
  {
    id: "filmes-populares",
    name: "Filmes Populares",
    emoji: "🎬",
    words: [
      "Titanic", "Avatar", "Vingadores Ultimato", "Homem-Aranha", "Batman", "Interestelar",
      "Top Gun Maverick", "Jurassic Park", "Matrix", "Gladiador", "O Senhor dos Anéis", "Harry Potter",
      "Jogos Vorazes", "Pantera Negra", "Deadpool", "Barbie", "Oppenheimer",
      "Transformers", "Missão Impossível", "John Wick", "Rocky",
      "Creed", "Forrest Gump", "Clube da Luta", "Se Beber Não Case", "A Origem",
      "Star Wars", "De Volta para o Futuro", "Indiana Jones", "Piratas do Caribe", "Velozes e Furiosos",
      "Homem de Ferro", "Capitão América", "Thor", "Guardiões da Galáxia", "Esqueceram de Mim",
      "MIB Homens de Preto", "Ghostbusters", "Edward Mãos de Tesoura", "A Fantástica Fábrica de Chocolate",
      "ET O Extraterrestre", "Tubarão", "Duna", "Legalmente Loira", "Meninas Malvadas",
      "Curtindo a Vida Adoidado", "As Branquelas", "Todo Mundo em Pânico", "Click", "Jumanji",
      "Independence Day", "Armageddon", "2012", "O Dia Depois de Amanhã", "King Kong",
      "Godzilla", "Crepúsculo", "As Crônicas de Nárnia", "Percy Jackson", "A Culpa é das Estrelas",
      "Ghost Do Outro Lado da Vida", "Dirty Dancing", "Grease", "Cantando na Chuva", "O Mágico de Oz",
      "O Sexto Sentido", "Atividade Paranormal", "Invocação do Mal", "It A Coisa", "Coringa",
      "Logan", "Mulher-Maravilha", "Esquadrão Suicida", "Quarteto Fantástico", "X-Men",
      "Homem-Formiga", "Doutor Estranho", "Aquaman", "Pânico", "Premonição",
      "Sexta-Feira 13", "A Hora do Pesadelo", "Halloween", "Exterminador do Futuro", "Rambo",
      "Duro de Matar", "Bad Boys", "Quase Famosos", "Escola de Rock", "As Patricinhas de Beverly Hills",
      "Simplesmente Acontece", "Diário de uma Paixão", "La La Land", "Os Miseráveis", "Bohemian Rhapsody",
      "Elvis", "Rocketman", "Nasce uma Estrela", "Mamma Mia", "Esposa de Mentirinha",
      "Gente Grande", "Shazam", "Venom", "Liga da Justiça", "Batman O Cavaleiro das Trevas",
      "Superman", "Homem de Aço", "Animais Fantásticos", "Jogos Mortais", "Truque de Mestre",
      "Sherlock Holmes", "Free Guy", "Alerta Vermelho", "Resgate", "Agente Oculto", "Planeta dos Macacos"
    ]
  },
  {
    id: "filmes-infantis",
    name: "Filmes Infantis",
    emoji: "🍿",
    words: [
      "Shrek", "Minions", "Frozen", "Divertida Mente", "Procurando Nemo", "Procurando Dory",
      "Toy Story", "Moana", "Encanto", "Coco", "Monstros S.A.", "Universidade Monstros",
      "Carros", "Carros 2", "Carros 3", "Ratatouille", "Wall-E", "Up",
      "Valente", "Luca", "Red Crescer é uma Fera", "A Pequena Sereia", "Aladdin",
      "Mulan", "Tarzan", "O Rei Leão", "Bambi", "Dumbo", "Pinóquio",
      "Branca de Neve", "Cinderela", "A Bela e a Fera", "Enrolados", "Zootopia",
      "Sing", "Meu Malvado Favorito", "Madagascar", "Kung Fu Panda", "Os Croods",
      "Hotel Transilvânia", "Gato de Botas", "Operação Big Hero", "Detona Ralph", "Os Incríveis",
      "A Era do Gelo", "Pica-Pau", "Madagascar 2", "Madagascar 3", "Kung Fu Panda 2",
      "Kung Fu Panda 3", "Como Treinar o Seu Dragão", "Megamente", "Os Pinguins de Madagascar",
      "Bolt", "Planeta do Tesouro", "Atlantis", "Irmão Urso", "Lilo & Stitch",
      "Pocahontas", "Hércules", "Vida de Inseto", "Dois Irmãos Uma Jornada Fantástica", "Soul",
      "Turning Red", "Elementos", "Wish", "O Bom Dinossauro", "Os Smurfs",
      "Alvin e os Esquilos", "Pets A Vida Secreta dos Bichos", "Sing 2", "Angry Birds",
      "Trolls", "O Poderoso Chefinho", "Pequeno Príncipe", "Gnomeu e Julieta", "Paranorman",
      "Coraline", "A Noiva Cadáver", "Frankenweenie", "O Estranho Mundo de Jack", "A Viagem de Chihiro",
      "Meu Amigo Totoro", "Ponyo", "O Castelo Animado", "Mulan 2", "O Rei Leão 2", "Tarzan 2"
    ]
  },
  {
    id: "series-populares",
    name: "Séries Populares",
    emoji: "📺",
    words: [
      "Todo Mundo Odeia o Chris", "Chaves", "Chapolin", "Bob Esponja", "Os Simpsons", "Pica-Pau",
      "Scooby-Doo", "Tom e Jerry", "Ben 10", "Hora de Aventura", "Os Jovens Titãs", "Pokémon",
      "Dragon Ball Z", "Naruto", "Friends", "The Office", "Eu, a Patroa e as Crianças", "Um Maluco no Pedaço",
      "Todo Mundo em Pânico", "ICarly", "Drake & Josh", "Hannah Montana", "Zack & Cody", "As Visões da Raven",
      "Grey's Anatomy", "The Walking Dead", "Stranger Things", "Round 6", "Wandinha", "Cobra Kai",
      "Brooklyn 99", "Breaking Bad", "Game of Thrones", "House", "Lost", "Supernatural",
      "The Flash", "Smallville", "Loki", "The Mandalorian"
    ]
  },
  {
    id: "atores-atrizes",
    name: "Atores e Atrizes",
    emoji: "🎭",
    words: [
      "Tom Hanks", "Leonardo DiCaprio", "Brad Pitt", "Angelina Jolie", "Jennifer Aniston", 
      "Scarlett Johansson", "Robert Downey Jr", "Chris Evans", "Chris Hemsworth", "Emma Watson", 
      "Daniel Radcliffe", "Morgan Freeman", "Will Smith", "Dwayne Johnson", "Keanu Reeves", 
      "Johnny Depp", "Natalie Portman", "Anne Hathaway", "Margot Robbie", "Ryan Reynolds", 
      "Ryan Gosling", "Zendaya", "Tom Holland", "Gal Gadot", "Henry Cavill", 
      "Jenna Ortega", "Jim Carrey", "Adam Sandler", "Robin Williams", "Tom Cruise", 
      "Harrison Ford", "Bruce Willis", "Nicolas Cage", "Vin Diesel", "Jason Statham", 
      "Mark Wahlberg", "Chris Pratt", "Millie Bobby Brown", "Timothée Chalamet", "Robert Pattinson", 
      "Kristen Stewart", "Orlando Bloom", "Hugh Jackman", "Al Pacino", "Robert De Niro", 
      "Arnold Schwarzenegger", "Sylvester Stallone", "Jackie Chan", "Cameron Diaz", "Reese Witherspoon"
    ]
  },
  {
    id: "personagens-famosos",
    name: "Personagens Famosos",
    emoji: "🦸",
    words: [
      "Harry Potter", "Hermione", "Ron Weasley", "Homem-Aranha", "Batman", "Superman",
      "Mulher-Maravilha", "Homem de Ferro", "Capitão América", "Thor", "Hulk", "Loki",
      "Darth Vader", "Yoda", "Luke Skywalker", "Elsa", "Anna", "Olaf",
      "Mickey Mouse", "Pateta", "Pato Donald", "Buzz Lightyear", "Woody", "Shrek",
      "Burro", "Gato de Botas", "Pikachu", "Mario", "Luigi", "Sonic",
      "Tails", "Naruto", "Sasuke", "Goku", "Vegeta", "Luffy",
      "Zoro", "Scooby-Doo", "Salsicha", "Bob Esponja", "Patrick", "Peppa Pig",
      "Simba", "Mufasa", "Aladdin", "Genie", "Mulan", "Tarzan",
      "Pernalonga", "Coringa", "Deadpool", "Pantera Negra", "Wolverine", "Homem-Formiga",
      "Doutor Estranho", "Aquaman", "Flash", "Lanterna Verde", "Robin", "Charada",
      "Pinguim", "Mulher-Gato", "Harley Quinn", "Thanos", "Venom",
      "Miles Morales", "Gwen Stacy", "Optimus Prime", "Bumblebee", "Megatron",
      "Jack Sparrow", "Indiana Jones", "Katniss Everdeen", "Sherlock Holmes", "James Bond",
      "Gandalf", "Frodo", "Gollum", "Ash Ketchum", "Misty",
      "Charmander", "Bulbasaur", "Squirtle", "Pac-Man", "Steve",
      "Alex", "Princess Peach", "Bowser", "Yoshi", "Minnie Mouse",
      "Margarida", "Pluto", "Pica-Pau", "Tom", "Jerry",
      "Frajola", "Piu-Piu", "Taz", "Gaguinho", "Pantera Cor-de-Rosa"
    ]
  },
  {
    id: "bandas-famosas",
    name: "Bandas Famosas",
    emoji: "🎸",
    words: [
      "The Beatles", "Queen", "Coldplay", "Imagine Dragons", "Maroon 5", "Linkin Park",
      "U2", "Bon Jovi", "Metallica", "Nirvana", "Red Hot Chili Peppers", "ABBA",
      "Bee Gees", "Aerosmith", "Guns N Roses", "Kiss", "Pink Floyd", "The Rolling Stones",
      "AC/DC", "OneRepublic", "Legião Urbana", "Titãs", "Skank", "Jota Quest",
      "Roupa Nova", "Paralamas do Sucesso", "NX Zero", "Charlie Brown Jr", "Evanescence", "Black Eyed Peas"
    ]
  },
  {
    id: "musicos-famosos",
    name: "Músicos Famosos",
    emoji: "🎤",
    words: [
      "Taylor Swift", "Ed Sheeran", "Bruno Mars", "Adele", "Beyoncé", "Michael Jackson",
      "Elvis Presley", "Madonna", "Justin Bieber", "Lady Gaga", "Shakira", "Rihanna",
      "Billie Eilish", "Drake", "Eminem", "The Weeknd", "Anitta", "Ivete Sangalo",
      "Roberto Carlos", "Luan Santana", "Gusttavo Lima", "Marília Mendonça", "Jorge", "Mateus",
      "Zezé Di Camargo", "Luciano", "Alok", "Djavan", "Caetano Veloso", "Gilberto Gil",
      "Elton John", "Freddie Mercury", "John Lennon", "Paul McCartney", "Miley Cyrus", "Selena Gomez",
      "Olivia Rodrigo", "Sabrina Carpenter", "Post Malone", "Katy Perry"
    ]
  },
  {
    id: "animais",
    name: "Animais",
    emoji: "🐾",
    words: [
      "Leão", "Elefante", "Girafa", "Macaco", "Zebra", "Tigre", "Urso", "Lobo", "Raposa", "Coelho",
      "Canguru", "Koala", "Panda", "Hipopótamo", "Rinoceronte", "Crocodilo", "Jacaré", "Tartaruga", "Serpente", "Sapo",
      "Águia", "Coruja", "Papagaio", "Pinguim", "Flamingo", "Avestruz", "Galinha", "Pato", "Ganso", "Peru",
      "Baleia", "Golfinho", "Tubarão", "Polvo", "Medusa", "Caranguejo", "Estrela-do-mar", "Camarão", "Cavalo-marinho", "Foca",
      "Cachorro", "Gato", "Cavalo", "Vaca", "Porco", "Ovelha", "Cabra", "Burro", "Camelo", "Lhama",
      "Abelha", "Borboleta", "Formiga", "Mosquito", "Aranha", "Escorpião", "Besouro", "Joaninha", "Gafanhoto", "Libélula",
      "Morcego", "Esquilo", "Gambá", "Guaxinim", "Castor", "Toupeira", "Hiena", "Chita", "Gorila", "Chimpanzé",
      "Tubarão-martelo", "Arraia", "Enguia", "Pelicano", "Gaivota", "Cisne", "Tucano", "Pica-pau", "Falcão", "Pombo",
      "Camaleão", "Iguana", "Lagarto", "Cascavel", "Jiboia", "Salmão", "Atum", "Tilápia", "Sardinha", "Carpa",
      "Ouriço", "Tatu", "Tamanduá", "Preguiça", "Ornitorrinco", "Mamute", "Búfalo", "Alce", "Rena", "Tubarão-branco"
    ]
  },
  {
    id: "corpo-humano",
    name: "Corpo Humano",
    emoji: "🫀",
    words: [
      "Sola do pé", "Peito do pé", "Calcanhar", "Dedo do pé", "Tornozelo",
      "Panturrilha", "Canela", "Joelho", "Coxa", "Virilha",
      "Umbigo", "Costela", "Clavícula", "Pescoço", "Garganta",
      "Nuca", "Ombro", "Axila", "Cotovelo", "Antebraço",
      "Pulso", "Palma da mão", "Dedo indicador", "Mão fechada", "Unhas",
      "Fio de cabelo", "Sobrancelha", "Cílios", "Pálpebra", "Lóbulo da orelha",
      "Narina", "Bochecha", "Queixo", "Céu da boca", "Língua",
      "Dente do siso", "Gengiva", "Amígdalas", "Mandíbula",
      "Coração", "Pulmão", "Estômago", "Fígado", "Rins",
      "Cérebro", "Intestino", "Pâncreas", "Baço", "Vesícula",
      "Bexiga", "Apêndice", "Tireoide",
      "Osso", "Coluna vertebral", "Crânio", "Medula espinhal",
      "Veias", "Artérias", "Sangue", "Suor", "Lágrimas",
      "Saliva", "Cera de ouvido", "Musculatura", "Articulação", "Coração batendo"
    ]
  },
  {
    id: "pessoas-famosas",
    name: "Pessoas Famosas",
    emoji: "🌟",
    words: [
      "Neymar", "Pelé", "Cristiano Ronaldo", "Lionel Messi", "Michael Jordan", "Usain Bolt",
      "Ayrton Senna", "Lewis Hamilton", "Bill Gates", "Steve Jobs", "Elon Musk", "Mark Zuckerberg",
      "Oprah Winfrey", "Princesa Diana", "Rei Charles III", "Papa Francisco", "Albert Einstein", "Isaac Newton",
      "Marie Curie", "Stephen Hawking", "Walt Disney", "MrBeast", "Whindersson Nunes", "Felipe Neto",
      "Virginia Fonseca", "Silvio Santos", "Xuxa", "Faustão", "Gisele Bündchen", "Mahatma Gandhi",
      "Nelson Mandela", "Martin Luther King Jr", "Abraham Lincoln", "Cleópatra", "Júlio César", "Napoleão",
      "Dom Pedro I", "Santos Dumont", "Tarsila do Amaral", "Machado de Assis", "Monteiro Lobato", "J. K. Rowling",
      "Stephen King", "Greta Thunberg", "Malala", "Tony Hawk", "Ronaldo Fenômeno", "Ronaldinho Gaúcho",
      "Kobe Bryant", "LeBron James", "Jesus Cristo", "Moisés", "Leonardo da Vinci", "Pablo Picasso",
      "Vincent van Gogh", "William Shakespeare", "Beethoven", "Mozart", "Charles Darwin", "Galileu Galilei",
      "Ana Maria Braga", "Luciano Huck", "Ratinho", "Eliana", "Rodrigo Faro",
      "Casimiro", "Gaules", "Luva de Pedreiro", "Carlinhos Maia", "Tirullipa",
      "Tom Brady", "Mike Tyson", "Muhammad Ali", "Serena Williams", "Simone Biles",
      "Ana Hickmann", "Sabrina Sato", "Datena", "Chico Xavier", "Madre Teresa",
      "Che Guevara", "Winston Churchill", "Rainha Elizabeth II", "Príncipe William", "Barack Obama",
      "Donald Trump", "J
